exclude: 'venv/'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-xml
    -   id: debug-statements
    -   id: check-case-conflict
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.3.0
    hooks:
    -   id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.4
    hooks:
    -   id: isort
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.641
    hooks:
    -   id: mypy
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.24.0
    hooks:
    -   id: yapf
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.9.1
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
-   repo: https://github.com/asottile/yesqa
    rev: v0.0.8
    hooks:
    -   id: yesqa
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        description: This hook triggers pytest.
        entry: pytest -n 4  --maxfail=10
        language: python
        pass_filenames: false
