version: '3.7'
services:
    webapp:
        image: losdetective/mindpalace:latest
        env_file: .env
        ports:
            - '43960:8000'
        depends_on:
            - mongo
            - redis

    mongo:
        image: mongo:latest
        volumes:
            - mongo_data:/data/db
        command: mongod
        ports:
            - '43961:27017'

    redis:
        image: redis:latest
        command: redis-server --appendonly yes
        volumes:
            - redis_data:/data
        ports:
            - '43962:6379'
volumes:
    mongo_data:
    redis_data:
