version: '3.7'
services:
    webapp:
        image: losdetective/mindpalace:latest
        env_file: .env
        ports:
            - '43960:8000'
        volumes:
            - ./app:/home/mindpalace/app
            - ./deploy:/home/mindpalace/deploy
            - ./manage.py:/home/mindpalace/manage.py
            - ./config.py:/home/mindpalace/config.py
        depends_on:
            - mongo
            - redis

    mongo:
        image: mongo:latest
        volumes:
            - mongo_data:/data/db
        command: mongod -auth
        ports:
            - '43961:27017'

    redis:
        image: redis:latest
        command: redis-server --appendonly yes
        volumes:
            - redis_data:/data
        ports:
            - '43962:6379'

    nginx:
        image: nginx:latest
        environment:
            - APP_HOST=webapp
        volumes:
            - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ${SSL_CERT_PATH}/cert.pem:/etc/cert.pem
            - ${SSL_CERT_PATH}/key.pem:/etc/key.pem
            - ./app/static:/home/mindpalace/static
        ports:
            - '80:80'
            - '443:443'
        depends_on:
            - webapp
volumes:
    mongo_data:
    redis_data:
