version: '3'
services:
    webapp:
        image: mindpalace
        ports:
            - '8000:8000'

    mongo:
        image: mongo:latest
        command: mongod --port 27018
        ports:
            - '27018:27018'

    redis:
        image: redis:latest
        command: redis-server --appendonly yes
        ports:
            - '6379:6379'
