version: '3.7'
services:
    webapp:
        build: 
            context: .
            cache_from:
                - python:3.6-alpine
        image: mindpalace:latest
        ports:
            - '43960:8000'
        depends_on:
            - mongo
            - redis
        env_file: .compose_env

    mongo:
        image: mongo:latest
        command: mongod --port 27018
        volumes:
            - /data/db:/data/db
        ports:
            - '43961:27018'

    redis:
        image: redis:latest
        command: redis-server --appendonly yes
        volumes:
            - /data/db:/data
        ports:
            - '43962:6379'
