version: '3.7'
services:
    webapp:
        build: 
            context: .
            cache_from:
                - python:3.6-alpine
        image: mindpalace:latest
        ports:
            - '8000:8000'
        depends_on:
            - mongo
            - redis
        env_file: .env

    mongo:
        image: mongo:latest
        command: mongod --port 27018
        ports:
            - '27018:27018'

    redis:
        image: redis:latest
        command: redis-server --appendonly yes
        ports:
            - '6300:6379'
