version: '3.7'
services:
    webapp:
        image: losdetective/mindpalace:latest
        env_file: .env
        ports:
            - '43960:8000'
        volumes:
            - static_file:/home/mindpalace/app/static
        depends_on:
            - mongo
            - redis

    mongo:
        image: mongo:latest
        volumes:
            - mongo_data:/data/db
        command: mongod
        ports:
            - '43961:27017'

    redis:
        image: redis:latest
        command: redis-server --appendonly yes
        volumes:
            - redis_data:/data
        ports:
            - '43962:6379'
    nginx:
        image: nginx:latest
        environment:
            - APP_HOST=webapp
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - /home/hzy/myfile/certs/cert.pem:/etc/cert.pem
            - /home/hzy/myfile/certs/key.pem:/etc/key.pem
            - static_file:/home/mindpalace/static
        ports:
            - '80:80'
            - '443:443'
        depends_on:
            - webapp
volumes:
    mongo_data:
    redis_data:
    static_file:
