version: '3.7'
services:
    mongo:
        image: mongo:latest
        command: mongod -auth
        ports:
            - '43961:27017'
        restart: always
        volumes:
            - mongo_data:/data/db

    redis:
        image: redis:latest
        command: redis-server --appendonly yes
        ports:
            - '43962:6379'
        restart: always
        volumes:
            - redis_data:/data

    webapp:
        image: losdetective/mindpalace:latest
        entrypoint: gunicorn -w 4 manage:app -b 0.0.0.0:8000 --chdir /home/mindpalace
        env_file: .env
        ports:
            - '43960:8000'
        pull: true
        restart: always
        volumes:
            - ./app:/home/mindpalace/app
            - ./manage.py:/home/mindpalace/manage.py
            - ./config.py:/home/mindpalace/config.py
        depends_on:
            - mongo
            - redis

    redis_worker:
        image: losdetective/mindpalace:latest
        entrypoint: python3 /home/mindpalace/manage.py run_worker
        env_file: .env
        restart: always
        volumes:
            - ./app:/home/mindpalace/app
            - ./manage.py:/home/mindpalace/manage.py
            - ./config.py:/home/mindpalace/config.py
        depends_on:
            - mongo
            - redis

    nginx:
        image: nginx:latest
        env_file: .env
        environment:
            - APP_HOST=webapp
        ports:
            - '80:80'
            - '443:443'
        restart: always
        volumes:
            - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ${SSL_CERT_PATH}/cert.pem:/etc/cert.pem
            - ${SSL_CERT_PATH}/key.pem:/etc/key.pem
            - ./app/static:/home/mindpalace/static
        depends_on:
            - webapp
volumes:
    mongo_data:
    redis_data:
